import Fir.Wasm.Emit.ResidentArray

namespace Fir.Wasm.Emit.ResidentIlluminatePlayer

open Fir.Wasm
open Fir.Wasm.Concrete
open Lean

/-!
# Illuminate compiler-specialization closure

Lean 4.32 emits four private, application-specific specializations for the
animation player without serializing their bodies for downstream compilation.
This module implements those exact specializations inside Wasm.  They are not
host callbacks: they execute against the resident Natural, Array, String, and
constructor layouts in module-owned memory.

The helpers deliberately implement only the call shapes generated by
`Illuminate.Animation.Player`: both range loops have unit stride, the
parameter loop's upper bound is `paramMap.size`, and the pause loop's upper
bound is the range stop.  The linker checks all four imported signatures and
fails closed if Lean changes the specialization frontier.
-/

inductive LinkError where
  | invalidInput (error : SymbolicError)
  | incompatibleMemory
  | missingDependency (name : Name)
  | reservedDeclaration (name : Name)
  | unexpectedExternalInventory (names : Array String)
  | missingSpecialization (label : String)
  | duplicateSpecialization (label : String)
  | incompatibleSpecialization (label : String)
  | invalidOutput (error : SymbolicError)
  deriving Inhabited, Repr

private def u32 (value : Nat) : UInt32 := UInt32.ofNat value

def naturalFromU32Name : Name := `fir_illuminate_natural_from_u32
def oneFieldConstructorName : Name := `fir_illuminate_ctor_tag1_1
def attributeUpdateConstructorName : Name := `fir_illuminate_attribute_update
def productConstructorName : Name := `fir_illuminate_product
def textContentDecisionName : Name := `fir_illuminate_is_text_content
def optionNatEqName : Name := `fir_illuminate_option_nat_eq
def findSegmentLoopName : Name := `fir_illuminate_find_segment_loop
def parameterUpdatesLoopName : Name := `fir_illuminate_parameter_updates_loop
def findCrossedPauseLoopName : Name := `fir_illuminate_find_crossed_pause_loop

def helperNames : Array Name := #[
  naturalFromU32Name,
  oneFieldConstructorName,
  attributeUpdateConstructorName,
  productConstructorName,
  textContentDecisionName,
  optionNatEqName,
  findSegmentLoopName,
  parameterUpdatesLoopName,
  findCrossedPauseLoopName]

private def p0 : FVarId := ⟨`p0⟩
private def p1 : FVarId := ⟨`p1⟩
private def p2 : FVarId := ⟨`p2⟩
private def p3 : FVarId := ⟨`p3⟩
private def p4 : FVarId := ⟨`p4⟩

private def addressLocal : FVarId := ⟨`address⟩
private def rawLocal : FVarId := ⟨`raw⟩
private def savedScratchLocal : FVarId := ⟨`savedScratch⟩
private def tobjectResultLocal : FVarId := ⟨`tobjectResult⟩
private def objectResultLocal : FVarId := ⟨`objectResult⟩
private def uint8ResultLocal : FVarId := ⟨`uint8Result⟩
private def indexLocal : FVarId := ⟨`index⟩
private def indexHighLocal : FVarId := ⟨`indexHigh⟩
private def indexNatLocal : FVarId := ⟨`indexNat⟩
private def sizeLocal : FVarId := ⟨`size⟩
private def sizeNatLocal : FVarId := ⟨`sizeNat⟩
private def secondSizeLocal : FVarId := ⟨`secondSize⟩
private def secondSizeNatLocal : FVarId := ⟨`secondSizeNat⟩
private def frameLocal : FVarId := ⟨`frame⟩
private def frameHighLocal : FVarId := ⟨`frameHigh⟩
private def segmentLocal : FVarId := ⟨`segment⟩
private def startNatLocal : FVarId := ⟨`startNat⟩
private def countNatLocal : FVarId := ⟨`countNat⟩
private def startLocal : FVarId := ⟨`start⟩
private def countLocal : FVarId := ⟨`count⟩
private def highLocal : FVarId := ⟨`high⟩
private def endLocal : FVarId := ⟨`end⟩
private def bindingLocal : FVarId := ⟨`binding⟩
private def valueLocal : FVarId := ⟨`value⟩
private def elementLocal : FVarId := ⟨`element⟩
private def attributeLocal : FVarId := ⟨`attribute⟩
private def targetLocal : FVarId := ⟨`target⟩
private def updateLocal : FVarId := ⟨`update⟩
private def updatesLocal : FVarId := ⟨`updates⟩
private def matchesLocal : FVarId := ⟨`matches⟩
private def leftValueLocal : FVarId := ⟨`leftValue⟩
private def rightValueLocal : FVarId := ⟨`rightValue⟩
private def stopNatLocal : FVarId := ⟨`stopNat⟩
private def stopLocal : FVarId := ⟨`stop⟩
private def stepLocal : FVarId := ⟨`step⟩
private def optionLocal : FVarId := ⟨`option⟩

private def loopLabel : FVarId := ⟨`loop⟩

private def storeAddress (kind : AbiKind) (offset : Nat)
    (value : List Instruction) : List Instruction :=
  [.localGet addressLocal] ++ value ++ [.i32Store kind (u32 offset)]

private def constructorHeader (tag fields allocationBytes : Nat) : List Instruction :=
  storeAddress .uint32 headerKindOffset
      [.i32Const .uint32 ObjectKind.constructor.code] ++
    storeAddress .uint32 headerFlagsOffset
      [.i32Const .uint32 liveFlag] ++
    storeAddress .uint32 headerRefCountOffset
      [.i32Const .uint32 1] ++
    storeAddress .uint32 headerAllocationBytesOffset
      [.i32Const .uint32 (u32 allocationBytes)] ++
    storeAddress .uint32 headerAux0Offset
      [.i32Const .uint32 (u32 tag)] ++
    storeAddress .uint32 headerAux1Offset
      [.i32Const .uint32 (u32 fields)] ++
    storeAddress .uint32 headerAux2Offset
      [.i32Const .uint32 0] ++
    storeAddress .uint32 headerAux3Offset
      [.i32Const .uint32 0]

private def retypeRaw (result : AbiKind) (resultLocal : FVarId) :
    List Instruction := [
  .i32Const .uint32 0,
  .i32Load .uint32 0,
  .localSet savedScratchLocal,
  .i32Const .uint32 0,
  .localGet rawLocal,
  .i32Store .uint32 0,
  .i32Const .uint32 0,
  .i32Load result 0,
  .localSet resultLocal,
  .i32Const .uint32 0,
  .localGet savedScratchLocal,
  .i32Store .uint32 0,
  .localGet resultLocal,
  .ret]

private def trapUnlessZero (localId : FVarId) : List Instruction := [
  .localGet localId,
  .i32Const .uint32 0,
  .i32Eq,
  .ifElse [] [.unreachable]]

private def decodeNatural32 (source low high : FVarId) : List Instruction := [
  .localGet source,
  .call (.declaration ResidentNumeric.validateNaturalName),
  .localGet source,
  .call (.declaration ResidentNumeric.naturalLowName),
  .localSet low,
  .localGet source,
  .call (.declaration ResidentNumeric.naturalHighName),
  .localSet high] ++ trapUnlessZero high

private def callArraySize (array : FVarId) (sizeNat size : FVarId) :
    List Instruction := [
  .i32Const .erased 0,
  .localGet array,
  .call (.declaration (ResidentArray.externalName `Array.size)),
  .localSet sizeNat,
  .localGet sizeNat,
  .call (.declaration ResidentNumeric.naturalLowName),
  .localSet size]

private def callArrayGet (array index result : FVarId) : List Instruction := [
  .i32Const .erased 0,
  .localGet array,
  .localGet index,
  .i32Const .erased 0,
  .call (.declaration (ResidentArray.externalName `Array.getInternalBorrowed)),
  .localSet result]

def naturalFromU32Function : Function := {
  name := naturalFromU32Name
  params := #[(p0, .uint32)]
  results := #[.tobject]
  locals := #[(rawLocal, .uint32), (savedScratchLocal, .uint32),
    (tobjectResultLocal, .tobject)]
  body := [
    .localGet p0,
    .i32Const .uint32 0,
    .call (.declaration ResidentNumeric.makeNaturalName),
    .localSet rawLocal] ++ retypeRaw .tobject tobjectResultLocal }

/-- Layout shared by `Option.some` and `PatchTarget.attribute`. -/
def oneFieldConstructorFunction : Function := {
  name := oneFieldConstructorName
  params := #[(p0, .tobject)]
  results := #[.tobject]
  locals := #[(addressLocal, .uint32), (rawLocal, .uint32),
    (savedScratchLocal, .uint32), (tobjectResultLocal, .tobject)]
  body := [
    .i32Const .uint32 (u32 (headerBytes + target.semanticSlotBytes)),
    .call (.declaration ResidentAllocator.allocateName),
    .localSet addressLocal] ++
    constructorHeader 1 1 (headerBytes + target.semanticSlotBytes) ++
    storeAddress .tobject headerBytes [.localGet p0] ++ [
    .localGet addressLocal,
    .localSet rawLocal] ++ retypeRaw .tobject tobjectResultLocal }

def attributeUpdateConstructorFunction : Function := {
  name := attributeUpdateConstructorName
  params := #[(p0, .tobject), (p1, .tobject), (p2, .tobject)]
  results := #[.tobject]
  locals := #[(addressLocal, .uint32), (rawLocal, .uint32),
    (savedScratchLocal, .uint32), (tobjectResultLocal, .tobject)]
  body := [
    .i32Const .uint32 (u32 (headerBytes + 3 * target.semanticSlotBytes)),
    .call (.declaration ResidentAllocator.allocateName),
    .localSet addressLocal] ++
    constructorHeader 0 3 (headerBytes + 3 * target.semanticSlotBytes) ++
    storeAddress .tobject headerBytes [.localGet p0] ++
    storeAddress .tobject (headerBytes + target.semanticSlotBytes) [.localGet p1] ++
    storeAddress .tobject (headerBytes + 2 * target.semanticSlotBytes) [.localGet p2] ++ [
    .localGet addressLocal,
    .localSet rawLocal] ++ retypeRaw .tobject tobjectResultLocal }

def productConstructorFunction : Function := {
  name := productConstructorName
  params := #[(p0, .tobject), (p1, .tobject)]
  results := #[.object]
  locals := #[(addressLocal, .uint32), (rawLocal, .uint32),
    (savedScratchLocal, .uint32), (objectResultLocal, .object)]
  body := [
    .i32Const .uint32 (u32 (headerBytes + 2 * target.semanticSlotBytes)),
    .call (.declaration ResidentAllocator.allocateName),
    .localSet addressLocal] ++
    constructorHeader 0 2 (headerBytes + 2 * target.semanticSlotBytes) ++
    storeAddress .tobject headerBytes [.localGet p0] ++
    storeAddress .tobject (headerBytes + target.semanticSlotBytes) [.localGet p1] ++ [
    .localGet addressLocal,
    .localSet rawLocal] ++ retypeRaw .object objectResultLocal }

private def textContentBytes : List UInt8 :=
  "textContent".toUTF8.data.toList

private def compareTextByte (byte : UInt8) (index : Nat) : List Instruction := [
  .localGet p0,
  .i32Load8U .uint32 (u32 (headerBytes + index)),
  .i32Const .uint32 (u32 byte.toNat),
  .i32Eq,
  .localGet matchesLocal,
  .i32And,
  .localSet matchesLocal]

def textContentDecisionFunction : Function := {
  name := textContentDecisionName
  params := #[(p0, .object)]
  results := #[.uint32]
  locals := #[(matchesLocal, .uint32), (rawLocal, .uint32)]
  body := [
    .localGet p0,
    .i32Load .uint32 (u32 headerKindOffset),
    .i32Const .uint32 ObjectKind.string.code,
    .i32Eq,
    .ifElse [] [.unreachable],
    .localGet p0,
    .i32Load .uint32 (u32 headerAux0Offset),
    .i32Const .uint32 stringUtf8Marker,
    .i32Eq,
    .ifElse [] [.unreachable],
    .localGet p0,
    .i32Load .uint32 (u32 headerAux1Offset),
    .i32Const .uint32 (u32 textContentBytes.length),
    .i32Eq,
    .ifElse
      ([.i32Const .uint32 1, .localSet matchesLocal] ++
        (textContentBytes.zipIdx.flatMap fun (byte, index) =>
          compareTextByte byte index) ++
        [.localGet matchesLocal, .localSet rawLocal])
      [.i32Const .uint32 0, .localSet rawLocal],
    .localGet rawLocal,
    .ret] }

def optionNatEqFunction : Function := {
  name := optionNatEqName
  params := #[(p0, .tobject), (p1, .tobject)]
  results := #[.uint8]
  locals := #[(leftValueLocal, .tobject), (rightValueLocal, .tobject),
    (rawLocal, .uint32), (savedScratchLocal, .uint32),
    (uint8ResultLocal, .uint8)]
  body := [
    .localGet p0,
    .i32Const .tobject 1,
    .i32Eq,
    .ifElse
      [.localGet p1,
        .i32Const .tobject 1,
        .i32Eq,
        .localSet rawLocal]
      [.localGet p1,
        .i32Const .tobject 1,
        .i32Eq,
        .ifElse
          [.i32Const .uint32 0, .localSet rawLocal]
          [.localGet p0,
            .i32Load .tobject (u32 headerBytes),
            .localSet leftValueLocal,
            .localGet p1,
            .i32Load .tobject (u32 headerBytes),
            .localSet rightValueLocal,
            .localGet leftValueLocal,
            .localGet rightValueLocal,
            .call (.declaration (ResidentNumeric.externalName `Nat.decEq)),
            .ret]]] ++
    retypeRaw .uint8 uint8ResultLocal }

private def advanceIndex : List Instruction := [
  .localGet indexLocal,
  .i32Const .uint32 1,
  .i32Add,
  .localSet indexLocal,
  .br loopLabel]

def findSegmentLoopFunction : Function := {
  name := findSegmentLoopName
  params := #[(p0, .tobject), (p1, .object), (p2, .tobject)]
  results := #[.tobject]
  locals := #[(frameLocal, .uint32), (frameHighLocal, .uint32),
    (indexLocal, .uint32), (indexHighLocal, .uint32),
    (indexNatLocal, .tobject), (sizeNatLocal, .tagged),
    (sizeLocal, .uint32), (segmentLocal, .object),
    (startNatLocal, .tobject), (countNatLocal, .tobject),
    (startLocal, .uint32), (countLocal, .uint32),
    (highLocal, .uint32), (endLocal, .uint32),
    (optionLocal, .tobject)]
  body := decodeNatural32 p0 frameLocal frameHighLocal ++
    decodeNatural32 p2 indexLocal indexHighLocal ++
    callArraySize p1 sizeNatLocal sizeLocal ++ [
    .loop loopLabel [
      .localGet indexLocal,
      .localGet sizeLocal,
      .i32LtU,
      .ifElse
        ([.localGet indexLocal,
          .call (.declaration naturalFromU32Name),
          .localSet indexNatLocal] ++
          callArrayGet p1 indexNatLocal segmentLocal ++ [
          .localGet segmentLocal,
          .i32Load .tobject (u32 headerBytes),
          .localSet startNatLocal,
          .localGet segmentLocal,
          .i32Load .tobject (u32 (headerBytes + target.semanticSlotBytes)),
          .localSet countNatLocal] ++
          decodeNatural32 startNatLocal startLocal highLocal ++
          decodeNatural32 countNatLocal countLocal highLocal ++ [
          .localGet frameLocal,
          .localGet startLocal,
          .i32LtU,
          .ifElse advanceIndex [
            .localGet startLocal,
            .localGet countLocal,
            .i32Add,
            .localSet endLocal,
            .localGet endLocal,
            .localGet startLocal,
            .i32LtU,
            .ifElse [.unreachable] [],
            .localGet frameLocal,
            .localGet endLocal,
            .i32LtU,
            .ifElse
              [.localGet indexNatLocal,
                .call (.declaration oneFieldConstructorName),
                .localSet optionLocal,
                .localGet optionLocal,
                .ret]
              advanceIndex]])
        []],
    .i32Const .tobject 1,
    .ret] }

def parameterUpdatesLoopFunction : Function := {
  name := parameterUpdatesLoopName
  params := #[(p0, .object), (p1, .object), (p2, .object),
    (p3, .object), (p4, .tobject)]
  results := #[.object]
  locals := #[(indexLocal, .uint32), (indexHighLocal, .uint32),
    (indexNatLocal, .tobject), (sizeNatLocal, .tagged),
    (sizeLocal, .uint32), (secondSizeNatLocal, .tagged),
    (secondSizeLocal, .uint32), (bindingLocal, .object),
    (valueLocal, .object), (elementLocal, .tobject),
    (attributeLocal, .object), (targetLocal, .tobject),
    (updateLocal, .tobject), (updatesLocal, .object)]
  body := decodeNatural32 p4 indexLocal indexHighLocal ++
    callArraySize p0 sizeNatLocal sizeLocal ++
    callArraySize p1 secondSizeNatLocal secondSizeLocal ++ [
    .localGet p3,
    .localSet updatesLocal,
    .loop loopLabel [
      .localGet indexLocal,
      .localGet sizeLocal,
      .i32LtU,
      .ifElse
        ([.localGet indexLocal,
          .localGet secondSizeLocal,
          .i32LtU,
          .ifElse
            ([.localGet indexLocal,
              .call (.declaration naturalFromU32Name),
              .localSet indexNatLocal] ++
              callArrayGet p0 indexNatLocal bindingLocal ++
              callArrayGet p1 indexNatLocal valueLocal ++ [
              .localGet bindingLocal,
              .i32Load .tobject (u32 headerBytes),
              .localSet elementLocal,
              .localGet bindingLocal,
              .i32Load .object (u32 (headerBytes + target.semanticSlotBytes)),
              .localSet attributeLocal,
              .localGet attributeLocal,
              .call (.declaration textContentDecisionName),
              .ifElse
                [.i32Const .tobject 1, .localSet targetLocal]
                [.localGet attributeLocal,
                  .call (.declaration oneFieldConstructorName),
                  .localSet targetLocal],
              .localGet elementLocal,
              .localGet targetLocal,
              .localGet valueLocal,
              .call (.declaration attributeUpdateConstructorName),
              .localSet updateLocal,
              .i32Const .erased 0,
              .localGet updatesLocal,
              .localGet updateLocal,
              .call (.declaration (ResidentArray.externalName `Array.push)),
              .localSet updatesLocal])
            []] ++ advanceIndex)
        []],
    .localGet updatesLocal,
    .ret] }

def findCrossedPauseLoopFunction : Function := {
  name := findCrossedPauseLoopName
  params := #[(p0, .object), (p1, .object), (p2, .object), (p3, .tobject)]
  results := #[.object]
  locals := #[(indexLocal, .uint32), (indexHighLocal, .uint32),
    (indexNatLocal, .tobject), (stopNatLocal, .tobject),
    (stopLocal, .uint32), (highLocal, .uint32),
    (sizeNatLocal, .tagged), (sizeLocal, .uint32),
    (stepLocal, .object), (optionLocal, .tobject)]
  body := decodeNatural32 p3 indexLocal indexHighLocal ++ [
    .localGet p1,
    .i32Load .tobject (u32 (headerBytes + target.semanticSlotBytes)),
    .localSet stopNatLocal] ++
    decodeNatural32 stopNatLocal stopLocal highLocal ++
    callArraySize p0 sizeNatLocal sizeLocal ++ [
    .loop loopLabel [
      .localGet indexLocal,
      .localGet stopLocal,
      .i32LtU,
      .ifElse
        ([.localGet indexLocal,
          .localGet sizeLocal,
          .i32LtU,
          .ifElse
            ([.localGet indexLocal,
              .call (.declaration naturalFromU32Name),
              .localSet indexNatLocal] ++
              callArrayGet p0 indexNatLocal stepLocal ++ [
              .localGet stepLocal,
              .i32Load8U .uint32
                (u32 (headerBytes + target.semanticSlotBytes)),
              .ifElse
                [.localGet indexNatLocal,
                  .call (.declaration oneFieldConstructorName),
                  .call (.declaration oneFieldConstructorName),
                  .localSet optionLocal,
                  .localGet optionLocal,
                  .i32Const .tobject 1,
                  .call (.declaration productConstructorName),
                  .ret]
                []])
            []] ++ advanceIndex)
        []],
    .localGet p2,
    .ret] }

def functions : Array Function := #[
  naturalFromU32Function,
  oneFieldConstructorFunction,
  attributeUpdateConstructorFunction,
  productConstructorFunction,
  textContentDecisionFunction,
  optionNatEqFunction,
  findSegmentLoopFunction,
  parameterUpdatesLoopFunction,
  findCrossedPauseLoopFunction]

/--
Compiler ancestors pulled in while reconstructing `Float.ofScientific` leave
these unreachable declarations in the pre-pruned source module.  The final
dead-code pass removes them; pinning the list here still rejects a genuinely
new resident-runtime dependency.
-/
private def dormantExternalNames : Array String := #[
  "Nat.pow",
  "Nat.mul",
  "Nat.log2",
  "Nat.shiftRight",
  "UInt64.ofNat",
  "UInt64.toFloat",
  "Float.scaleB",
  "Nat.shiftLeft",
  "Nat.div",
  "Int.neg",
  "Int.mul"]

private structure Specialization where
  label : String
  declaration : Name
  replacement : Name
  signature : Signature

private def findSpecialization (module : Module) (label : String)
    (predicate : String → Bool) (replacement : Name)
    (signature : Signature) : Except LinkError Specialization := do
  let names := module.imports.filterMap (fun import_ => import_.declaration?) |>.filter
    (fun name => predicate name.toString)
  if names.isEmpty then throw (.missingSpecialization label)
  unless names.size == 1 do throw (.duplicateSpecialization label)
  let declaration := names[0]!
  let imports := module.imports.filter (fun import_ =>
    import_.declaration? == some declaration)
  unless imports.size == 1 && imports[0]!.signature == signature do
    throw (.incompatibleSpecialization label)
  return { label, declaration, replacement, signature }

private partial def rewriteInstruction
    (specializations : Array Specialization) : Instruction → Instruction
  | .call (.declaration declaration) =>
      match specializations.find? (fun specialization =>
          specialization.declaration == declaration) with
      | some specialization => .call (.declaration specialization.replacement)
      | none => .call (.declaration declaration)
  | .block label body =>
      .block label (body.map (rewriteInstruction specializations))
  | .loop label body =>
      .loop label (body.map (rewriteInstruction specializations))
  | .ifElse thenBody elseBody =>
      .ifElse (thenBody.map (rewriteInstruction specializations))
        (elseBody.map (rewriteInstruction specializations))
  | instruction => instruction

def internalize (module : Module) : Except LinkError Module := do
  match Fir.Wasm.validateModule module with
  | .ok () => pure ()
  | .error error => throw (.invalidInput error)
  unless module.memory == some ResidentRuntime.residentMemory do
    throw .incompatibleMemory
  for dependency in #[
      ResidentAllocator.allocateName,
      ResidentNumeric.validateNaturalName,
      ResidentNumeric.naturalLowName,
      ResidentNumeric.naturalHighName,
      ResidentNumeric.makeNaturalName,
      ResidentNumeric.externalName `Nat.decEq,
      ResidentArray.externalName `Array.size,
      ResidentArray.externalName `Array.getInternalBorrowed,
      ResidentArray.externalName `Array.push] do
    unless module.functions.any (fun function => function.name == dependency) do
      throw (.missingDependency dependency)
  for name in helperNames do
    if module.imports.any (fun import_ => import_.declaration? == some name) ||
        module.functions.any (fun function => function.name == name) ||
        module.exports.contains name then
      throw (.reservedDeclaration name)
  let findSegment ← findSpecialization module "findSegment"
    (fun name => name.startsWith
      "Array.findIdx?.loop._at_.Illuminate.AnimationPlayer.findSegment.spec_")
    findSegmentLoopName {
      params := #[.tobject, .object, .tobject], results := #[.tobject] }
  let parameterUpdates ← findSpecialization module "parameterUpdates"
    (fun name => name.contains "Range.forIn'.loop" &&
      name.contains "Illuminate.AnimationPlayer.parameterUpdates.spec_")
    parameterUpdatesLoopName {
      params := #[.object, .object, .object, .object, .tobject],
      results := #[.object] }
  let optionEq ← findSpecialization module "Option BEq"
    (fun name => name.startsWith "Option.instBEq.beq._at_.")
    optionNatEqName {
      params := #[.tobject, .tobject], results := #[.uint8] }
  let crossedPause ← findSpecialization module "findCrossedPause"
    (fun name => name.contains "Range.forIn'.loop" &&
      name.contains "Illuminate.AnimationPlayer.findCrossedPause.spec_")
    findCrossedPauseLoopName {
      params := #[.object, .object, .object, .tobject], results := #[.object] }
  let specializations := #[findSegment, parameterUpdates, optionEq, crossedPause]
  let externalNames := module.imports.filterMap (fun import_ => import_.declaration?)
  let dormantNames := externalNames.filter (fun name =>
    !specializations.any (fun specialization =>
      specialization.declaration == name))
  unless externalNames.size == specializations.size + dormantExternalNames.size &&
      specializations.all (fun specialization =>
        externalNames.contains specialization.declaration) &&
      dormantNames.size == dormantExternalNames.size &&
      dormantNames.all (fun name => dormantExternalNames.contains name.toString) do
    throw (.unexpectedExternalInventory (externalNames.map Name.toString))
  let linkedFunctions := module.functions.map (fun candidate =>
    let body := candidate.body.map (rewriteInstruction specializations)
    { candidate with body })
  let linkedFunctions := linkedFunctions ++ functions
  let declarations := specializations.map (fun specialization =>
    specialization.declaration)
  let result : Module := {
    module with
    functions := linkedFunctions
    imports := module.imports.filter (fun import_ =>
      !(import_.declaration?).any declarations.contains)
    exports := helperNames.foldl Fir.Wasm.addUnique module.exports
    runtimeOperations := Fir.Wasm.collectRuntimeOps linkedFunctions }
  match Fir.Wasm.validateModule result with
  | .ok () => return result
  | .error error => throw (.invalidOutput error)

end Fir.Wasm.Emit.ResidentIlluminatePlayer
