import FirTalos.TrustAuditCore

/-!
Exact inventories measured at W6 `7affa1d2` on 2026-09-09.
Generated axioms are existing debt recorded by
FIR-BUG-wasm-none-endpoint-native-axiom-audit, not newly approved assumptions.
Changes require review of each affected endpoint; there are no wildcard rules.
-/

namespace FirTalos.TrustAudit

def compilerExportNativeDebt : Array String := #[
  "Fir.Wasm.boxResultKind_uint16_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_uint16_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_uint16_tobject._native.native_decide.ax_1_3",
  "Fir.Wasm.boxResultKind_uint32_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_uint32_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_uint32_tobject._native.native_decide.ax_1_3",
  "Fir.Wasm.boxResultKind_uint64_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_uint64_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_uint64_tobject._native.native_decide.ax_1_3",
  "Fir.Wasm.boxResultKind_uint8_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_usize_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_usize_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_usize_tobject._native.native_decide.ax_1_3",
  "FirTalos.Concrete.scalarUInt8Local_eq_of_related._native.native_decide.ax_1_1",
  "FirTalos.Correctness.constructorTag_uint8_eq_iff._native.native_decide.ax_1_1",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_11",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_12",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_13",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_14",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_15",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_9",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_1",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_2",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_3",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_4",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_5",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_6",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_7",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_8",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_9",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_1",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_3",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_4",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_5",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_6",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_7",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_1",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_11",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_12",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_13",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_14",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_2",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_3",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_4",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_5",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_6",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_7",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_8",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_9",
  "Fir.Wasm.Concrete.LiveHeapRel.readBoxedScalar_tagged_refines._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.LiveHeapRel.readBoxedScalar_tagged_refines._native.native_decide.ax_1_11",
  "Fir.Wasm.Concrete.LiveHeapRel.readBoxedScalar_tagged_refines._native.native_decide.ax_1_9",
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte16._native.bv_decide.ax_1_6",
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte32._native.bv_decide.ax_1_6"]

/-- Measured against the original validated direct-let proof at `14a2b07f`.
The frame-preserving and root-preserving wrappers inherit exactly this debt;
root transport adds no axiom. This is an inventory, not new trust approval. -/
def directLetNativeDebt : Array String := #[
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_1",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_11",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_12",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_13",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_14",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_2",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_3",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_4",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_5",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_6",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_7",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_8",
  "Fir.Wasm.Concrete.BoxedScalarKind.allowsTaggedRepresentation_of_unbox_tagged_eq_ok._native.native_decide.ax_1_9",
  "Fir.Wasm.Concrete.LiveHeapRel.readBoxedScalar_tagged_refines._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.LiveHeapRel.readBoxedScalar_tagged_refines._native.native_decide.ax_1_11",
  "Fir.Wasm.Concrete.LiveHeapRel.readBoxedScalar_tagged_refines._native.native_decide.ax_1_9",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_11",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_12",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_13",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_14",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_15",
  "Fir.Wasm.Concrete.boxUsesTaggedRepresentation_boxedScalar._native.native_decide.ax_1_9",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_1",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_10",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_2",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_3",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_4",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_5",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_6",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_7",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_8",
  "Fir.Wasm.Concrete.scalarFromType_boxedScalarKind._native.native_decide.ax_1_9",
  "Fir.Wasm.boxResultKind_uint16_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_uint16_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_uint16_tobject._native.native_decide.ax_1_3",
  "Fir.Wasm.boxResultKind_uint32_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_uint32_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_uint32_tobject._native.native_decide.ax_1_3",
  "Fir.Wasm.boxResultKind_uint64_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_uint64_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_uint64_tobject._native.native_decide.ax_1_3",
  "Fir.Wasm.boxResultKind_uint8_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_usize_tobject._native.native_decide.ax_1_1",
  "Fir.Wasm.boxResultKind_usize_tobject._native.native_decide.ax_1_2",
  "Fir.Wasm.boxResultKind_usize_tobject._native.native_decide.ax_1_3",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_1",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_3",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_4",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_5",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_6",
  "FirTalos.Concrete.ConcreteRuntimeRel.boxScalarAtResultKind._native.native_decide.ax_1_7",
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte32._native.bv_decide.ax_1_6"]

/-- Existing scalar-case debt, measured before root transport at `3ddb98e8`.
The original validation-derived dispatcher was also measured at `381d915a`;
the rooted composition retains that exact set, with no new trust approval.
The exact inventories below require the original and new producers to agree. -/
def scalarCaseNativeDebt : Array String := #[
  "FirTalos.Concrete.scalarUInt8Local_eq_of_related._native.native_decide.ax_1_1",
  "FirTalos.Correctness.constructorTag_uint8_eq_iff._native.native_decide.ax_1_1"]

/-- Existing ordinary increment/decrement debt, measured at `2baabade` before
frame/root transport. Explicit delete and all three validation-derived rules
have the same measured dependency at `97b25f06`. Constructor-tag mutation
and its validation-derived rule share it at `23bccf86`; USize field mutation
shares it at `c42bc5d2`. Active-witness FVar/erased object-field effects and
their schema producers share it at `e5ea3914`. The external-ready host step
shares it at `a56c88ef`; its named-bind helper and rooted producer retain the
same exact set. The focused wrappers retain
precisely this dependency; this is an exact inventory, not a new trust approval. -/
def referenceCountNativeDebt : Array String := #[
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte32._native.bv_decide.ax_1_6"]

/-- Existing packed-scalar field mutation dependencies measured at `c42bc5d2`
before frame/root transport. The layout premise and exact dependency set are
retained, not discharged or newly approved. -/
def packedScalarFieldNativeDebt : Array String := #[
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte16._native.bv_decide.ax_1_6",
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte32._native.bv_decide.ax_1_6"]

def scalarInstallationNativeDebt : Array String := #[
  "FirTalos.Concrete.ResidentMemoryRel.read32_write32_self._native.bv_decide.ax_1_7",
  "FirTalos.Concrete.ResidentMemoryRel.write32_restore._native.bv_decide.ax_1_12",
  "FirTalos.Concrete.ResidentMemoryRel.write32_restore._native.bv_decide.ax_1_17",
  "FirTalos.Concrete.ResidentMemoryRel.write32_restore._native.bv_decide.ax_1_7",
  "FirTalos.Concrete.ResidentMemoryRel.writeUInt64._native.bv_decide.ax_1_13",
  "FirTalos.Concrete.ResidentMemoryRel.writeUInt64._native.bv_decide.ax_1_18",
  "FirTalos.Concrete.ResidentMemoryRel.writeUInt64._native.bv_decide.ax_1_23",
  "FirTalos.Concrete.ResidentMemoryRel.writeUInt64._native.bv_decide.ax_1_28",
  "FirTalos.Concrete.ResidentMemoryRel.writeUInt64._native.bv_decide.ax_1_33",
  "FirTalos.Concrete.ResidentMemoryRel.writeUInt64._native.bv_decide.ax_1_8",
  "FirTalos.Concrete.ResidentScalarBox.boxUInt64Object_physicalSignature._native.native_decide.ax_1_1",
  "FirTalos.Concrete.ResidentScalarBox.instructions_boxUInt64ObjectFunction._native.native_decide.ax_1_1",
  "FirTalos.Concrete.ResidentScalarBox.instructions_boxUInt64ObjectFunction._native.native_decide.ax_1_2",
  "FirTalos.Concrete.ResidentScalarBox.instructions_boxUInt64ObjectFunction._native.native_decide.ax_1_3",
  "FirTalos.Concrete.ResidentScalarBox.instructions_boxUInt64ObjectFunction._native.native_decide.ax_1_4",
  "FirTalos.Concrete.ResidentScalarBox.instructions_boxUInt64ObjectFunction._native.native_decide.ax_1_5",
  "FirTalos.Concrete.ResidentScalarBox.UInt64ObjectInstallation.signature._native.native_decide.ax_1_1",
  "FirTalos.Concrete.ResidentScalarBox.UInt64ObjectInstallation.signature._native.native_decide.ax_1_2",
  "FirTalos.Concrete.ResidentScalarBox.UInt64ObjectInstallation.signature._native.native_decide.ax_1_3",
  "_private.Fir.Wasm.Concrete.Memory.0.Fir.Wasm.Concrete.LinearMemory.assembleByte32._native.bv_decide.ax_1_6"]

def literalExampleNativeDebt : Array String := #[
  "FirTalos.compareObservations_returned_empty_tagged_42._native.native_decide.ax_1_5",
  "FirTalos.Correctness.abiLiteralAdaptedModule_adapted._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralCompileDecl._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralCompileDecl._native.native_decide.ax_1_2",
  "FirTalos.Correctness.abiLiteralCompileDecl._native.native_decide.ax_1_3",
  "FirTalos.Correctness.abiLiteralHostsMatch._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralImport_found._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralLocalSet._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_body._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_exported._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_found._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_notImport._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_resultCount._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_16",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_19",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_2",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_20",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_3",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_4",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_5",
  "FirTalos.Correctness.abiLiteralMain_simulation._native.native_decide.ax_1_6",
  "FirTalos.Correctness.abiLiteralResolvedHosts_operations._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralResolvedHosts_resolved._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralSourceFunction_found._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralSourceModule_lowered._native.native_decide.ax_1_1",
  "FirTalos.Correctness.abiLiteralSupportedExport._native.native_decide.ax_1"]

def endpointInventory : Array (Lean.Name × Array String) := #[
  (`FirTalos.Concrete.ConcreteRankedTraceSimulation.execSteps,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.finiteTraceCorrect_of_sourceInvariant,
    standardAxioms ++ compilerExportNativeDebt),
  (`FirTalos.Concrete.ConcreteSupportedExport.finiteTraceCorrect_of_schemaSourceInvariant,
    standardAxioms ++ compilerExportNativeDebt),
  (`FirTalos.Concrete.ConcreteFiniteTraceCorrect.precomposeStutteringPass,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.correctReturn,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.faultCorrectOfSimulation,
    standardAxioms),
  (`FirTalos.Concrete.ResidentReplacement.externalLetStepSimulates_of_definedCall,
    standardAxioms),
  (`FirTalos.Concrete.ResidentScalarBox.UInt64ObjectInstallation.terminatesWith_box_of_allocateBoxedScalar,
    standardAxioms ++ scalarInstallationNativeDebt),
  (`FirTalos.Correctness.abiLiteralMain_export_correct,
    standardAxioms ++ literalExampleNativeDebt),
  (`FirTalos.Concrete.sourcePrefixObservation_control_irrelevant,
    #[]),
  (`FirTalos.Concrete.returnedScalar_prefix_indistinguishable,
    #[]),
  (`FirTalos.Concrete.returnedScalar_outcomes_distinct,
    #[]),
  (`FirTalos.Concrete.finiteTraceCorrect_of_terminal_prefix,
    #["propext", "Classical.choice", "Quot.sound"]),
  (`FirTalos.Concrete.ConcreteExportTerminatesWith.postconditions_overlap,
    #["propext", "Classical.choice", "Quot.sound"]),
  (`FirTalos.Concrete.ConcreteExportTerminatesWith.not_trapsWith,
    #["propext", "Classical.choice", "Quot.sound"]),
  (`FirTalos.Concrete.RefinedReturnPost.uint64_values,
    #["propext", "Quot.sound"]),
  (`FirTalos.Concrete.ConcreteExportTerminatesWith.uint64_result_unique,
    #["propext", "Classical.choice", "Quot.sound"]),
  (`FirTalos.Concrete.ObservationSensitivity.prettyObservation_injective,
    #["propext"]),
  (`FirTalos.Concrete.ObservationSensitivity.prettyObservation_distinguishes_styling,
    #["propext"]),
  (`FirTalos.Concrete.ConcreteStructuredSupportedFrameStack.returning_halts,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredYieldFocus.refinedReturnPost,
    #["propext", "Quot.sound"]),
  (`FirTalos.Concrete.ConcreteStructuredYieldFocus.finitePath_halted,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedFunction.terminatesWith_of_structuredYield,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.terminatesWith_of_structuredYield,
    standardAxioms),
  (`FirTalos.Concrete.sourceCoreReturned_terminal,
    standardAxioms),
  (`FirTalos.Concrete.sourceExecReturned_terminal,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeGlobalOutcome.terminalYield_of_control,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedFunction.terminatesWith_of_validatedReturn,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.terminatesWith_of_validatedReturn,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredCodePointwiseRel.advance_return_precise,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_returnPrecise_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedFunction.terminatesWith_of_classifiedExecSteps,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.terminatesWith_of_classifiedExecEvaluates,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.terminatesWith_of_classifiedRun,
    standardAxioms),
  (`FirTalos.Concrete.concreteStructuredRootResultKind_nil,
    #[]),
  (`FirTalos.Concrete.concreteStructuredRootResultKind_push,
    #[]),
  (`FirTalos.Concrete.ConcreteStructuredValidatedStackAgreement.spine_eq_nil_of_empty,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidationAgreesAtRoot.toValidationAgrees,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidationAgrees.atRoot_of_empty,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidationAgreesAtRoot.functionResult_eq_of_empty,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidationAgreesAtRoot.case,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidationAgreesAtRoot.reindex,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteSupportedExport.validatedCodeRoot_rootResult,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedReturnedOutcome.yieldAtRoot_of_empty,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_returnPreciseAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_returnYieldAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_directLetWithFrames_of_step,
    standardAxioms ++ directLetNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_directLet_of_step,
    standardAxioms ++ directLetNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_directLetAtRoot_of_step,
    standardAxioms ++ directLetNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_defaultOnlyCaseWithFrames_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_defaultOnlyCase_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_defaultOnlyCaseAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectCasesWithFrames_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectCases_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectCasesAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarUInt8CasesWithFrames_of_step,
    standardAxioms ++ scalarCaseNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarUInt8Cases_of_step,
    standardAxioms ++ scalarCaseNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarUInt8CasesAtRoot_of_step,
    standardAxioms ++ scalarCaseNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_cases_of_validated_step,
    standardAxioms ++ scalarCaseNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_casesAtRoot_of_validated_step,
    standardAxioms ++ scalarCaseNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_incPersistent_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_incPersistentAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_decPersistent_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_decPersistentAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryIncrement_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryIncrementWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryIncrementAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDecrement_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDecrementWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDecrementAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDelete_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDeleteWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDeleteAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryIncrement_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryIncrementAtRoot_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDecrement_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDecrementAtRoot_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDelete_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_ordinaryDeleteAtRoot_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_constructorTag_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_constructorTagWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_constructorTagAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_constructorTag_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_constructorTagAtRoot_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_usizeField_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_usizeFieldWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_usizeFieldAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_usizeField_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_usizeFieldAtRoot_of_validated_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarField_of_step,
    standardAxioms ++ packedScalarFieldNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarFieldWithFrames_of_step,
    standardAxioms ++ packedScalarFieldNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarFieldAtRoot_of_step,
    standardAxioms ++ packedScalarFieldNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarField_of_validated_step,
    standardAxioms ++ packedScalarFieldNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_scalarFieldAtRoot_of_validated_step,
    standardAxioms ++ packedScalarFieldNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldFVarAt_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldFVarAtWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldFVarAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldFVar_of_schema_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldFVarAtRoot_of_schema_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldErasedAt_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldErasedAtWithFrames_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldErasedAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldErased_of_schema_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_objectFieldErasedAtRoot_of_schema_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_directCall_stage_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_directCall_stageAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_saturatedCall_stage_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_saturatedCall_stageAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_lazy_stage_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_lazy_stageAtRoot_of_step,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_pureExternal_stage,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedCodeOutcome.advance_pureExternal_stageAtRoot,
    standardAxioms),
  (`FirTalos.Concrete.ConcreteStructuredValidatedExternalCallReadyOutcome.advance_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedExternalCallReadyOutcome.advance_bind_of_step,
    standardAxioms ++ referenceCountNativeDebt),
  (`FirTalos.Concrete.ConcreteStructuredValidatedExternalCallReadyOutcome.advance_bindAtRoot_of_step,
    standardAxioms ++ referenceCountNativeDebt)]

end FirTalos.TrustAudit
