name = "FirTalos"
version = "0.1.0"
defaultTargets = ["FirTalos"]
packagesDir = "../talos/.lake/packages"

[[require]]
name = "Fir"
path = "../../.."

[[require]]
name = "Interpreter"
path = "../talos/interpreter"

[[lean_lib]]
name = "FirTalos"
